"""Strategy templates, methods, and intent models."""

from .attribution import (
    ENTRY_ATTRIBUTION_INDICATOR_REQUIREMENTS,
    ATTRIBUTION_FACTOR_SELECTION_SCHEMA,
    AttributionFactorDeclaration,
    EntryAttributionContext,
    EntryAttributionEvidence,
    EntryAttributionEvidenceDateIndex,
    EntryAttributionFilterCondition,
    EntryAttributionFilterRule,
    EntryAttributionFactorDeclaration,
    apply_entry_attribution_filter,
    attribution_declaration_by_key,
    attribution_factor_declarations,
    attribution_factor_keys,
    attribution_factor_declaration_payload,
    build_entry_attribution_context,
    entry_attribution_declaration_by_key,
    entry_attribution_factor_keys,
    entry_attribution_factor_declarations,
    entry_attribution_payload,
    resolve_attribution_factor_selection,
    with_enabled_entry_attribution_factors,
    with_entry_attribution_controls,
    with_entry_attribution_evidence,
    with_sizing_attribution,
)
from .contract import (
    STRATEGY_OUTPUT_CONTRACT_SCHEMA,
    StrategyOutputContractIssue,
    build_strategy_output_contract,
    trade_intent_satisfies_output_contract,
    validate_trade_intent_output_contract,
)
from .integration_template import (
    STRATEGY_INTEGRATION_TEMPLATE_SCHEMA,
    build_strategy_integration_template,
    render_strategy_integration_template_markdown_zh,
)
from .intents import TradeIntent, TradeIntentType

__all__ = [
    "ENTRY_ATTRIBUTION_INDICATOR_REQUIREMENTS",
    "ATTRIBUTION_FACTOR_SELECTION_SCHEMA",
    "STRATEGY_INTEGRATION_TEMPLATE_SCHEMA",
    "STRATEGY_OUTPUT_CONTRACT_SCHEMA",
    "AttributionFactorDeclaration",
    "EntryAttributionContext",
    "EntryAttributionEvidence",
    "EntryAttributionEvidenceDateIndex",
    "EntryAttributionFilterCondition",
    "EntryAttributionFilterRule",
    "EntryAttributionFactorDeclaration",
    "StrategyOutputContractIssue",
    "TradeIntent",
    "TradeIntentType",
    "apply_entry_attribution_filter",
    "attribution_declaration_by_key",
    "attribution_factor_declarations",
    "attribution_factor_keys",
    "attribution_factor_declaration_payload",
    "build_entry_attribution_context",
    "build_strategy_integration_template",
    "build_strategy_output_contract",
    "entry_attribution_declaration_by_key",
    "entry_attribution_factor_keys",
    "entry_attribution_factor_declarations",
    "render_strategy_integration_template_markdown_zh",
    "resolve_attribution_factor_selection",
    "trade_intent_satisfies_output_contract",
    "validate_trade_intent_output_contract",
    "entry_attribution_payload",
    "with_enabled_entry_attribution_factors",
    "with_entry_attribution_controls",
    "with_entry_attribution_evidence",
    "with_sizing_attribution",
]
