"""Feature and indicator calculations."""

from .aggregation import MarketFeatureRow, MarketIndicators, join_bars_with_indicators
from .alignment import CompletedIndicatorEvidence, completed_indicator_before_event
from .frame import (
    IndicatorFrame,
    build_indicator_frame,
    build_indicator_snapshots,
    build_indicator_snapshots_for_requirements,
    indicator_frame_from_snapshots,
    indicator_snapshots_from_frame,
    indicator_snapshots_from_frame_for_requirements,
)
from .indicators import (
    ATRValue,
    KDJValue,
    MACDValue,
    MAValue,
    RSIValue,
    calculate_atr,
    calculate_kdj,
    calculate_macd,
    calculate_rsi,
    calculate_sma,
)
from .planning import IndicatorUpdatePlan, build_indicator_update_plans
from .registry import (
    DEFAULT_INDICATOR_NAMES,
    SUPPORTED_ATR_PERIODS,
    SUPPORTED_INDICATOR_NAMES,
    SUPPORTED_INDICATOR_TIMEFRAMES,
    SUPPORTED_MA_PERIODS,
    SUPPORTED_RSI_PERIODS,
    IndicatorRequirement,
    IndicatorSpec,
    atr_indicator_name,
    indicator_names_for_timeframe,
    indicator_period,
    indicator_spec,
    indicator_set_name,
    ma_indicator_name,
    normalize_indicator_names,
    normalize_indicator_requirements,
    rsi_indicator_name,
)
from .snapshots import (
    IndicatorSnapshotMetadata,
    IndicatorSnapshot,
    IndicatorSnapshotCandidate,
    discover_indicator_snapshot_paths,
    indicator_snapshot_metadata_path,
    indicator_snapshot_path,
    merge_indicator_snapshots,
    read_indicator_snapshot_metadata,
    read_indicator_snapshots_parquet,
    write_indicator_snapshot_metadata,
    write_merged_indicator_snapshots_parquet,
    write_indicator_snapshots_parquet,
)
from .state import (
    STATEFUL_INDICATOR_NAMES,
    build_indicator_snapshots_from_state,
    indicator_states_from_bars,
)

__all__ = [
    "IndicatorFrame",
    "IndicatorSnapshot",
    "IndicatorSnapshotCandidate",
    "IndicatorSnapshotMetadata",
    "IndicatorSpec",
    "IndicatorUpdatePlan",
    "CompletedIndicatorEvidence",
    "ATRValue",
    "KDJValue",
    "MACDValue",
    "MAValue",
    "MarketFeatureRow",
    "MarketIndicators",
    "RSIValue",
    "DEFAULT_INDICATOR_NAMES",
    "SUPPORTED_ATR_PERIODS",
    "SUPPORTED_INDICATOR_NAMES",
    "SUPPORTED_INDICATOR_TIMEFRAMES",
    "SUPPORTED_MA_PERIODS",
    "SUPPORTED_RSI_PERIODS",
    "STATEFUL_INDICATOR_NAMES",
    "IndicatorRequirement",
    "atr_indicator_name",
    "calculate_atr",
    "build_indicator_frame",
    "build_indicator_snapshots",
    "build_indicator_snapshots_from_state",
    "build_indicator_snapshots_for_requirements",
    "build_indicator_update_plans",
    "calculate_kdj",
    "calculate_macd",
    "calculate_rsi",
    "calculate_sma",
    "completed_indicator_before_event",
    "discover_indicator_snapshot_paths",
    "indicator_frame_from_snapshots",
    "indicator_names_for_timeframe",
    "indicator_period",
    "indicator_spec",
    "indicator_set_name",
    "indicator_snapshots_from_frame",
    "indicator_snapshots_from_frame_for_requirements",
    "indicator_snapshot_path",
    "indicator_snapshot_metadata_path",
    "indicator_states_from_bars",
    "join_bars_with_indicators",
    "ma_indicator_name",
    "merge_indicator_snapshots",
    "normalize_indicator_names",
    "normalize_indicator_requirements",
    "read_indicator_snapshots_parquet",
    "read_indicator_snapshot_metadata",
    "rsi_indicator_name",
    "write_merged_indicator_snapshots_parquet",
    "write_indicator_snapshot_metadata",
    "write_indicator_snapshots_parquet",
]
